// @stelis/contracts — shared TypeScript contract data for cross-package
// boundaries.
//
// Policy constraints:
//   - zero / minimal runtime scope;
//   - no runtime helper with Node-only or browser-only side effects;
//   - only request/response types, runtime data tables/identifiers/discriminator
//     literals, and trivial pure data-adjacent lookup functions.

export type {
  SuiNetwork,
  SettleProfile,
  SettlementSwapDirection,
  MoveCallCommand,
  PtbCommand,
  DeepBookPoolHop,
  SingleHopSettlementSwapPath,
  SingleHopSettlementSwapPathResponse,
  PrepareAuthorizationFields,
  ExpectedSettleEventFields,
} from './types.js';

export type {
  RelayStatusResponse,
  RelayConfigResponse,
  RelayPrepareRequest,
  RelayPrepareResponse,
  RelaySponsorRequest,
  RelaySponsorResponse,
  HostErrorResponse,
  HostErrorMeta,
  PromotionType,
  PromotionStatus,
  PromotionPageQuery,
  PromotionPageParams,
  AdminPromotionListQuery,
  PromotionUnavailableReason,
  PromotionListItem,
  PromotionListResponse,
  UserPromotionDetail,
  PromotionDetailResponse,
  PromotionEntitlementStatus,
  PromotionEntitlement,
  PromotionClaimRequest,
  PromotionClaimResponse,
  PromotionPrepareRequest,
  PromotionPrepareResponse,
  PromotionSponsorRequest,
  PromotionSponsorResponse,
  AdminAuthVerifyRequest,
  AdminSessionResponse,
  AdminAuditLogEntry,
  AdminBlockScope,
  AbuseBlockReason,
  AdminBlocklistEntry,
  AdminBlocklistQuery,
  AdminBlocklistParams,
  AdminBlocklistResponse,
  AdminBlocklistDeleteRequest,
  AdminBlocklistDeleteResponse,
  AdminStudioResponse,
  AdminPromotionRecord,
  AdminPromotionCreateRequest,
  AdminPromotionUpdateRequest,
  AdminPromotionStatusRequest,
  AdminSponsoredLogsMode,
  AdminSponsoredExecutionAggregate,
  AdminSponsoredExecutionLogEntry,
  SponsorRefillAccountWithdrawalRequest,
  AdminSponsorOperationsResponse,
  SuiRpcFleetStatus,
  HostOperatingMode,
  HostHealthResponse,
} from './hostWire.js';

export {
  HostWireParseError,
  PROMOTION_STATUSES,
  PROMOTION_PAGE_MAX_LIMIT,
  ADMIN_BLOCKLIST_MAX_LIMIT,
  ADMIN_BLOCKLIST_CURSOR_MAX_LENGTH,
  HOST_OPERATING_MODES,
  STUDIO_USER_ID_MAX_LENGTH,
  ABUSE_BLOCK_SCOPES,
  ABUSE_BLOCK_REASONS,
  isValidStudioUserId,
  parseHostHealthResponse,
  parseRelayStatusResponse,
  parseRelayConfigResponse,
  parseRelayPrepareRequest,
  parseRelayPrepareResponse,
  parseRelaySponsorRequest,
  parseRelaySponsorResponse,
  parseHostErrorResponse,
  parsePromotionListResponse,
  parsePromotionDetailResponse,
  parsePromotionClaimRequest,
  parsePromotionClaimResponse,
  parsePromotionPrepareRequest,
  parsePromotionPrepareResponse,
  parsePromotionSponsorRequest,
  parsePromotionSponsorResponse,
  parsePromotionPageQuery,
  parseAdminPromotionListQuery,
  isPromotionId,
  parsePromotionId,
  PROMOTION_ID_FORMAT,
  isReceiptId,
  parseReceiptId,
  RECEIPT_ID_FORMAT,
  comparePromotionIds,
  isPromotionStatus,
  parseAdminAuthChallengeResponse,
  parseAdminAuthVerifyRequest,
  parseAdminAuthSuccessResponse,
  parseAdminSessionResponse,
  parseAdminAuditLogEntry,
  parseAdminAuditLogsResponse,
  parseAdminBlocklistQuery,
  parseAdminBlocklistResponse,
  parseAdminBlocklistDeleteRequest,
  parseAdminBlocklistDeleteResponse,
  parseAdminStudioResponse,
  parseAdminPromotionListResponse,
  parseAdminPromotionDetailResponse,
  parseAdminPromotionSummaryResponse,
  parseAdminSettlementSwapPathsResponse,
  parseAdminPromotionCreateRequest,
  parseAdminPromotionUpdateRequest,
  parseAdminPromotionStatusRequest,
  parseAdminPromotionResponse,
  parseAdminPromotionDeleteResponse,
  parseAdminSponsoredLogsQuery,
  parseAdminSponsoredLogsSummaryResponse,
  parseAdminSponsoredLogsResponse,
  parseSponsorRefillAccountWithdrawalChallengeResponse,
  parseSponsorRefillAccountWithdrawalRequest,
  parseSponsorRefillAccountWithdrawalResponse,
  parseAdminSponsorOperationsResponse,
  canonicalizeSuiRpcOrigin,
} from './hostWire.js';

export type {
  RelayStatusErrorCode,
  RelayConfigErrorCode,
  StudioListErrorCode,
  StudioDetailErrorCode,
  StudioClaimErrorCode,
  RelayPrepareErrorCode,
  RelaySponsorErrorCode,
  PromotionPrepareErrorCode,
  PromotionSponsorErrorCode,
  HostErrorCode,
  HostErrorMetaField,
  SponsorFailureSubcode,
  PaymentInputIntegritySubcode,
  HostErrorSubcode,
} from './hostError.js';

export {
  RELAY_STATUS_ERROR_CODES,
  RELAY_CONFIG_ERROR_CODES,
  STUDIO_LIST_ERROR_CODES,
  STUDIO_DETAIL_ERROR_CODES,
  STUDIO_CLAIM_ERROR_CODES,
  RELAY_PREPARE_ERROR_CODES,
  RELAY_SPONSOR_ERROR_CODES,
  PROMOTION_PREPARE_ERROR_CODES,
  PROMOTION_SPONSOR_ERROR_CODES,
  ADMIN_REQUEST_ADMISSION_ERROR_CODES,
  ADMIN_AUTH_NONCE_ERROR_CODES,
  ADMIN_AUTH_VERIFY_ERROR_CODES,
  ADMIN_AUTH_LOGOUT_ERROR_CODES,
  ADMIN_SESSION_ERROR_CODES,
  ADMIN_READ_ERROR_CODES,
  ADMIN_BLOCKLIST_READ_ERROR_CODES,
  ADMIN_BLOCKLIST_DELETE_ERROR_CODES,
  ADMIN_SPONSORED_LOGS_ERROR_CODES,
  ADMIN_PROMOTION_LIST_ERROR_CODES,
  ADMIN_PROMOTION_READ_ERROR_CODES,
  ADMIN_PROMOTION_CREATE_ERROR_CODES,
  ADMIN_PROMOTION_UPDATE_ERROR_CODES,
  ADMIN_PROMOTION_STATUS_ERROR_CODES,
  ADMIN_PROMOTION_DELETE_ERROR_CODES,
  ADMIN_WITHDRAWAL_CHALLENGE_ERROR_CODES,
  ADMIN_WITHDRAWAL_ERROR_CODES,
  SPONSOR_FAILURE_SUBCODES,
  PAYMENT_INPUT_INTEGRITY_SUBCODES,
  HOST_ERROR_HTTP_STATUS,
  HOST_ERROR_META_POLICY,
  hostErrorPublicMessage,
  isHostErrorCode,
  isHostErrorSubcode,
} from './hostError.js';

export type {
  SettleVariantClass,
  SettleFieldValues,
  SettleEventFieldMoveType,
  SettleEventValue,
} from './settlementContract.js';

export {
  SETTLEMENT_CONTRACT_NETWORK,
  SETTLE_MODULE,
  SETTLE_WITH_CREDIT_FUNCTION,
  SETTLEMENT_ENTRY_FUNCTIONS,
  SETTLE_FUNCTIONS,
  settlementParameterIndex,
  SETTLEMENT_SWAP_DIRECTION_FUNCTIONS,
  settlementSwapDirectionFromFunctionName,
  SETTLE_FIELD_SCHEMA,
  SETTLE_EVENT_MODULE,
  SETTLE_EVENT_NAME,
  SETTLE_EVENT_FIELDS,
  SETTLE_ABORT,
  VAULT_ABORT,
  DEEPBOOK_MIN_OUT_ABORT,
} from './settlementContract.js';

export {
  MAX_PROMOTION_LEDGER_VALUE_MIST,
  NODE_TIMER_MAX_DELAY_MS,
  isNodeTimerDelayMs,
  SETTLEMENT_SWAP_DIRECTION_VECTORS,
  settlementSwapDirectionFromSwapDirections,
  SUI_TYPE,
  SUI_CHAIN_IDENTIFIERS,
  DEEPBOOK_RUNTIME_PACKAGE_ID,
  DEEPBOOK_IDS,
  STELIS_CONTRACT_IDS,
  requireContractId,
  SLIPPAGE_CAP_BPS,
  GAS_MARGIN_CAP_BPS,
} from './constants.js';

export type {
  SponsorSlotState,
  SponsorAvailabilityErrorCode,
  SponsorSlotLeaseSummary,
  SponsorOperationsStatus,
} from './admin.js';

export {
  buildSponsorRefillAccountWithdrawMessage,
  calculateSponsorAvailabilityErrorCode,
  isPositiveU64DecimalString,
  SPONSOR_SLOT_STATES,
} from './admin.js';
