// Generated by scripts/generate-settlement-contract.mjs from locked production Move bytecode.
// Do not edit by hand.

import type { SettlementSwapDirection } from './types.js';

export const SETTLEMENT_CONTRACT_NETWORK = 'testnet' as const;
export const SETTLE_MODULE = 'settle';
export const SETTLE_WITH_CREDIT_FUNCTION = 'settle_with_credit';

export type SettleVariantClass = 'new_user' | 'with_vault' | 'credit';

export interface SettlementTypeParameterDescriptor {
  readonly constraints: readonly string[];
}

export interface SettlementParameterDescriptor {
  readonly name: string;
  readonly moveType: string;
}

export const SETTLEMENT_ENTRY_FUNCTIONS = {
  swap_and_settle_new_user_bfq: {
    variantClass: 'new_user',
    typeParameters: [
      {
        constraints: [],
      },
    ],
    parameters: [
      {
        name: 'config',
        moveType:
          '&0x0000000000000000000000000000000000000000000000000000000000000000::config::Config',
      },
      {
        name: 'registry',
        moveType:
          '&mut 0x0000000000000000000000000000000000000000000000000000000000000000::vault::VaultRegistry',
      },
      {
        name: 'clock',
        moveType:
          '&0x0000000000000000000000000000000000000000000000000000000000000002::clock::Clock',
      },
      {
        name: 'pool',
        moveType:
          '&mut 0xfb28c4cbc6865bd1c897d26aecbe1f8792d1509a20ffec692c800660cbec6982::pool::Pool<T0, 0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>',
      },
      {
        name: 'payment_coin',
        moveType:
          '0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<T0>',
      },
      {
        name: 'swap_amount',
        moveType: 'u64',
      },
      {
        name: 'min_sui_out',
        moveType: 'u64',
      },
      {
        name: 'execution_cost_claim_mist',
        moveType: 'u64',
      },
      {
        name: 'settlement_payout_recipient',
        moveType: 'address',
      },
      {
        name: 'receipt_id',
        moveType: 'vector<u8>',
      },
      {
        name: 'nonce',
        moveType: 'u64',
      },
      {
        name: 'sim_gas_reported',
        moveType: 'u64',
      },
      {
        name: 'gas_variance_fixed_mist',
        moveType: 'u64',
      },
      {
        name: 'slippage_buffer_mist',
        moveType: 'u64',
      },
      {
        name: 'quoted_host_fee_mist',
        moveType: 'u64',
      },
      {
        name: 'expected_protocol_fee_mist',
        moveType: 'u64',
      },
      {
        name: 'expected_config_version',
        moveType: 'u64',
      },
      {
        name: 'quote_timestamp_ms',
        moveType: 'u64',
      },
      {
        name: 'policy_hash',
        moveType: 'vector<u8>',
      },
      {
        name: 'order_id_hash',
        moveType: 'vector<u8>',
      },
    ],
  },
  swap_and_settle_with_vault_bfq: {
    variantClass: 'with_vault',
    typeParameters: [
      {
        constraints: [],
      },
    ],
    parameters: [
      {
        name: 'config',
        moveType:
          '&0x0000000000000000000000000000000000000000000000000000000000000000::config::Config',
      },
      {
        name: 'registry',
        moveType:
          '&0x0000000000000000000000000000000000000000000000000000000000000000::vault::VaultRegistry',
      },
      {
        name: 'clock',
        moveType:
          '&0x0000000000000000000000000000000000000000000000000000000000000002::clock::Clock',
      },
      {
        name: 'user_vault',
        moveType:
          '&mut 0x0000000000000000000000000000000000000000000000000000000000000000::vault::UserVault',
      },
      {
        name: 'pool',
        moveType:
          '&mut 0xfb28c4cbc6865bd1c897d26aecbe1f8792d1509a20ffec692c800660cbec6982::pool::Pool<T0, 0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>',
      },
      {
        name: 'payment_coin',
        moveType:
          '0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<T0>',
      },
      {
        name: 'swap_amount',
        moveType: 'u64',
      },
      {
        name: 'min_sui_out',
        moveType: 'u64',
      },
      {
        name: 'execution_cost_claim_mist',
        moveType: 'u64',
      },
      {
        name: 'settlement_payout_recipient',
        moveType: 'address',
      },
      {
        name: 'receipt_id',
        moveType: 'vector<u8>',
      },
      {
        name: 'nonce',
        moveType: 'u64',
      },
      {
        name: 'sim_gas_reported',
        moveType: 'u64',
      },
      {
        name: 'gas_variance_fixed_mist',
        moveType: 'u64',
      },
      {
        name: 'slippage_buffer_mist',
        moveType: 'u64',
      },
      {
        name: 'quoted_host_fee_mist',
        moveType: 'u64',
      },
      {
        name: 'expected_protocol_fee_mist',
        moveType: 'u64',
      },
      {
        name: 'expected_config_version',
        moveType: 'u64',
      },
      {
        name: 'quote_timestamp_ms',
        moveType: 'u64',
      },
      {
        name: 'policy_hash',
        moveType: 'vector<u8>',
      },
      {
        name: 'order_id_hash',
        moveType: 'vector<u8>',
      },
      {
        name: 'use_credit_amount',
        moveType: 'u64',
      },
    ],
  },
  swap_and_settle_new_user_qfb: {
    variantClass: 'new_user',
    typeParameters: [
      {
        constraints: [],
      },
    ],
    parameters: [
      {
        name: 'config',
        moveType:
          '&0x0000000000000000000000000000000000000000000000000000000000000000::config::Config',
      },
      {
        name: 'registry',
        moveType:
          '&mut 0x0000000000000000000000000000000000000000000000000000000000000000::vault::VaultRegistry',
      },
      {
        name: 'clock',
        moveType:
          '&0x0000000000000000000000000000000000000000000000000000000000000002::clock::Clock',
      },
      {
        name: 'pool',
        moveType:
          '&mut 0xfb28c4cbc6865bd1c897d26aecbe1f8792d1509a20ffec692c800660cbec6982::pool::Pool<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI, T0>',
      },
      {
        name: 'payment_coin',
        moveType:
          '0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<T0>',
      },
      {
        name: 'swap_amount',
        moveType: 'u64',
      },
      {
        name: 'min_sui_out',
        moveType: 'u64',
      },
      {
        name: 'execution_cost_claim_mist',
        moveType: 'u64',
      },
      {
        name: 'settlement_payout_recipient',
        moveType: 'address',
      },
      {
        name: 'receipt_id',
        moveType: 'vector<u8>',
      },
      {
        name: 'nonce',
        moveType: 'u64',
      },
      {
        name: 'sim_gas_reported',
        moveType: 'u64',
      },
      {
        name: 'gas_variance_fixed_mist',
        moveType: 'u64',
      },
      {
        name: 'slippage_buffer_mist',
        moveType: 'u64',
      },
      {
        name: 'quoted_host_fee_mist',
        moveType: 'u64',
      },
      {
        name: 'expected_protocol_fee_mist',
        moveType: 'u64',
      },
      {
        name: 'expected_config_version',
        moveType: 'u64',
      },
      {
        name: 'quote_timestamp_ms',
        moveType: 'u64',
      },
      {
        name: 'policy_hash',
        moveType: 'vector<u8>',
      },
      {
        name: 'order_id_hash',
        moveType: 'vector<u8>',
      },
    ],
  },
  swap_and_settle_with_vault_qfb: {
    variantClass: 'with_vault',
    typeParameters: [
      {
        constraints: [],
      },
    ],
    parameters: [
      {
        name: 'config',
        moveType:
          '&0x0000000000000000000000000000000000000000000000000000000000000000::config::Config',
      },
      {
        name: 'registry',
        moveType:
          '&0x0000000000000000000000000000000000000000000000000000000000000000::vault::VaultRegistry',
      },
      {
        name: 'clock',
        moveType:
          '&0x0000000000000000000000000000000000000000000000000000000000000002::clock::Clock',
      },
      {
        name: 'user_vault',
        moveType:
          '&mut 0x0000000000000000000000000000000000000000000000000000000000000000::vault::UserVault',
      },
      {
        name: 'pool',
        moveType:
          '&mut 0xfb28c4cbc6865bd1c897d26aecbe1f8792d1509a20ffec692c800660cbec6982::pool::Pool<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI, T0>',
      },
      {
        name: 'payment_coin',
        moveType:
          '0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<T0>',
      },
      {
        name: 'swap_amount',
        moveType: 'u64',
      },
      {
        name: 'min_sui_out',
        moveType: 'u64',
      },
      {
        name: 'execution_cost_claim_mist',
        moveType: 'u64',
      },
      {
        name: 'settlement_payout_recipient',
        moveType: 'address',
      },
      {
        name: 'receipt_id',
        moveType: 'vector<u8>',
      },
      {
        name: 'nonce',
        moveType: 'u64',
      },
      {
        name: 'sim_gas_reported',
        moveType: 'u64',
      },
      {
        name: 'gas_variance_fixed_mist',
        moveType: 'u64',
      },
      {
        name: 'slippage_buffer_mist',
        moveType: 'u64',
      },
      {
        name: 'quoted_host_fee_mist',
        moveType: 'u64',
      },
      {
        name: 'expected_protocol_fee_mist',
        moveType: 'u64',
      },
      {
        name: 'expected_config_version',
        moveType: 'u64',
      },
      {
        name: 'quote_timestamp_ms',
        moveType: 'u64',
      },
      {
        name: 'policy_hash',
        moveType: 'vector<u8>',
      },
      {
        name: 'order_id_hash',
        moveType: 'vector<u8>',
      },
      {
        name: 'use_credit_amount',
        moveType: 'u64',
      },
    ],
  },
  settle_with_credit: {
    variantClass: 'credit',
    typeParameters: [],
    parameters: [
      {
        name: 'config',
        moveType:
          '&0x0000000000000000000000000000000000000000000000000000000000000000::config::Config',
      },
      {
        name: 'registry',
        moveType:
          '&0x0000000000000000000000000000000000000000000000000000000000000000::vault::VaultRegistry',
      },
      {
        name: 'clock',
        moveType:
          '&0x0000000000000000000000000000000000000000000000000000000000000002::clock::Clock',
      },
      {
        name: 'user_vault',
        moveType:
          '&mut 0x0000000000000000000000000000000000000000000000000000000000000000::vault::UserVault',
      },
      {
        name: 'use_credit_amount',
        moveType: 'u64',
      },
      {
        name: 'execution_cost_claim_mist',
        moveType: 'u64',
      },
      {
        name: 'settlement_payout_recipient',
        moveType: 'address',
      },
      {
        name: 'receipt_id',
        moveType: 'vector<u8>',
      },
      {
        name: 'nonce',
        moveType: 'u64',
      },
      {
        name: 'sim_gas_reported',
        moveType: 'u64',
      },
      {
        name: 'gas_variance_fixed_mist',
        moveType: 'u64',
      },
      {
        name: 'slippage_buffer_mist',
        moveType: 'u64',
      },
      {
        name: 'quoted_host_fee_mist',
        moveType: 'u64',
      },
      {
        name: 'expected_protocol_fee_mist',
        moveType: 'u64',
      },
      {
        name: 'expected_config_version',
        moveType: 'u64',
      },
      {
        name: 'quote_timestamp_ms',
        moveType: 'u64',
      },
      {
        name: 'policy_hash',
        moveType: 'vector<u8>',
      },
      {
        name: 'order_id_hash',
        moveType: 'vector<u8>',
      },
    ],
  },
} as const satisfies Readonly<
  Record<
    string,
    {
      readonly variantClass: SettleVariantClass;
      readonly typeParameters: readonly SettlementTypeParameterDescriptor[];
      readonly parameters: readonly SettlementParameterDescriptor[];
    }
  >
>;

export const SETTLE_FUNCTIONS: ReadonlySet<string> = new Set(
  Object.keys(SETTLEMENT_ENTRY_FUNCTIONS),
);

export function settlementParameterIndex(
  functionName: string,
  parameterName: string,
): number | undefined {
  const entry = (
    SETTLEMENT_ENTRY_FUNCTIONS as Readonly<
      Record<string, { readonly parameters: readonly SettlementParameterDescriptor[] } | undefined>
    >
  )[functionName];
  if (!entry) return undefined;
  const index = entry.parameters.findIndex((parameter) => parameter.name === parameterName);
  return index >= 0 ? index : undefined;
}

export const SETTLEMENT_SWAP_DIRECTION_FUNCTIONS: Record<
  SettlementSwapDirection,
  { readonly newUser: string; readonly withVault: string }
> = {
  baseForQuote: {
    newUser: 'swap_and_settle_new_user_bfq',
    withVault: 'swap_and_settle_with_vault_bfq',
  },
  quoteForBase: {
    newUser: 'swap_and_settle_new_user_qfb',
    withVault: 'swap_and_settle_with_vault_qfb',
  },
};

export function settlementSwapDirectionFromFunctionName(
  functionName: string,
): SettlementSwapDirection | undefined {
  for (const [direction, functions] of Object.entries(SETTLEMENT_SWAP_DIRECTION_FUNCTIONS)) {
    if (functions.newUser === functionName || functions.withVault === functionName) {
      return direction as SettlementSwapDirection;
    }
  }
  return undefined;
}

export type SettleFieldName =
  | 'executionCostClaim'
  | 'settlementPayoutRecipient'
  | 'receiptId'
  | 'nonce'
  | 'simGasReported'
  | 'gasVarianceFixedMist'
  | 'slippageBufferMist'
  | 'quotedHostFeeMist'
  | 'expectedProtocolFeeMist'
  | 'expectedConfigVersion'
  | 'quoteTimestampMs'
  | 'policyHash'
  | 'orderIdHash';
export type SettlementPureMoveType = 'u64' | 'address' | 'vector<u8>';

export interface SettleFieldDescriptor {
  readonly name: SettleFieldName;
  readonly moveName: string;
  readonly moveType: SettlementPureMoveType;
}

export const SETTLE_FIELD_SCHEMA = [
  {
    name: 'executionCostClaim',
    moveName: 'execution_cost_claim_mist',
    moveType: 'u64',
  },
  {
    name: 'settlementPayoutRecipient',
    moveName: 'settlement_payout_recipient',
    moveType: 'address',
  },
  {
    name: 'receiptId',
    moveName: 'receipt_id',
    moveType: 'vector<u8>',
  },
  {
    name: 'nonce',
    moveName: 'nonce',
    moveType: 'u64',
  },
  {
    name: 'simGasReported',
    moveName: 'sim_gas_reported',
    moveType: 'u64',
  },
  {
    name: 'gasVarianceFixedMist',
    moveName: 'gas_variance_fixed_mist',
    moveType: 'u64',
  },
  {
    name: 'slippageBufferMist',
    moveName: 'slippage_buffer_mist',
    moveType: 'u64',
  },
  {
    name: 'quotedHostFeeMist',
    moveName: 'quoted_host_fee_mist',
    moveType: 'u64',
  },
  {
    name: 'expectedProtocolFeeMist',
    moveName: 'expected_protocol_fee_mist',
    moveType: 'u64',
  },
  {
    name: 'expectedConfigVersion',
    moveName: 'expected_config_version',
    moveType: 'u64',
  },
  {
    name: 'quoteTimestampMs',
    moveName: 'quote_timestamp_ms',
    moveType: 'u64',
  },
  {
    name: 'policyHash',
    moveName: 'policy_hash',
    moveType: 'vector<u8>',
  },
  {
    name: 'orderIdHash',
    moveName: 'order_id_hash',
    moveType: 'vector<u8>',
  },
] as const satisfies readonly SettleFieldDescriptor[];

export interface SettleFieldValues {
  executionCostClaim: bigint;
  settlementPayoutRecipient: string;
  receiptId: Uint8Array;
  nonce: bigint;
  simGasReported: bigint;
  gasVarianceFixedMist: bigint;
  slippageBufferMist: bigint;
  quotedHostFeeMist: bigint;
  expectedProtocolFeeMist: bigint;
  expectedConfigVersion: bigint;
  quoteTimestampMs: bigint;
  policyHash: Uint8Array;
  orderIdHash: Uint8Array;
}

export const SETTLE_EVENT_MODULE = 'events';
export const SETTLE_EVENT_NAME = 'SettleEvent';
export type SettleEventFieldMoveType = 'u64' | 'address' | 'vector<u8>';

export interface SettleEventFieldDescriptor {
  readonly name: string;
  readonly index: number;
  readonly moveType: SettleEventFieldMoveType;
}

export const SETTLE_EVENT_FIELDS = [
  {
    name: 'receipt_id',
    index: 0,
    moveType: 'vector<u8>',
  },
  {
    name: 'nonce',
    index: 1,
    moveType: 'u64',
  },
  {
    name: 'policy_hash',
    index: 2,
    moveType: 'vector<u8>',
  },
  {
    name: 'quote_timestamp_ms',
    index: 3,
    moveType: 'u64',
  },
  {
    name: 'exec_timestamp_ms',
    index: 4,
    moveType: 'u64',
  },
  {
    name: 'sim_gas_reported',
    index: 5,
    moveType: 'u64',
  },
  {
    name: 'gas_variance_fixed_mist',
    index: 6,
    moveType: 'u64',
  },
  {
    name: 'slippage_buffer_mist',
    index: 7,
    moveType: 'u64',
  },
  {
    name: 'execution_cost_claim_mist',
    index: 8,
    moveType: 'u64',
  },
  {
    name: 'quoted_host_fee_mist',
    index: 9,
    moveType: 'u64',
  },
  {
    name: 'protocol_fee',
    index: 10,
    moveType: 'u64',
  },
  {
    name: 'protocol_treasury',
    index: 11,
    moveType: 'address',
  },
  {
    name: 'payout',
    index: 12,
    moveType: 'u64',
  },
  {
    name: 'total_in',
    index: 13,
    moveType: 'u64',
  },
  {
    name: 'surplus_credited',
    index: 14,
    moveType: 'u64',
  },
  {
    name: 'config_version',
    index: 15,
    moveType: 'u64',
  },
  {
    name: 'user',
    index: 16,
    moveType: 'address',
  },
  {
    name: 'settlement_payout_recipient',
    index: 17,
    moveType: 'address',
  },
  {
    name: 'order_id_hash',
    index: 18,
    moveType: 'vector<u8>',
  },
] as const satisfies readonly SettleEventFieldDescriptor[];

export interface SettleEventValue {
  receipt_id: Uint8Array;
  nonce: string;
  policy_hash: Uint8Array;
  quote_timestamp_ms: string;
  exec_timestamp_ms: string;
  sim_gas_reported: string;
  gas_variance_fixed_mist: string;
  slippage_buffer_mist: string;
  execution_cost_claim_mist: string;
  quoted_host_fee_mist: string;
  protocol_fee: string;
  protocol_treasury: string;
  payout: string;
  total_in: string;
  surplus_credited: string;
  config_version: string;
  user: string;
  settlement_payout_recipient: string;
  order_id_hash: Uint8Array;
}

export const SETTLE_ABORT = {
  EPaused: 100,
  EClaimTooHigh: 101,
  ETotalInTooLow: 102,
  EInsufficientFunds: 103,
  EInvalidReceiptId: 104,
  EInvalidPolicyHash: 105,
  EConfigVersionMismatch: 106,
  EProtocolFeeMismatch: 107,
  EHostFeeCapExceeded: 108,
  EInvalidOrderIdHash: 109,
  ESpreadTooWide: 110,
} as const satisfies Record<string, number>;
export const VAULT_ABORT = {
  EInsufficientBalance: 0,
  EReplayNonce: 1,
  EVaultAlreadyRegistered: 2,
  EVaultNotRegistered: 3,
  EVaultMismatch: 4,
} as const satisfies Record<string, number>;
export const DEEPBOOK_MIN_OUT_ABORT = {
  runtimePackageId: '0xfb28c4cbc6865bd1c897d26aecbe1f8792d1509a20ffec692c800660cbec6982',
  modulePath: 'pool::swap_exact_quantity',
  constantName: 'EMinimumQuantityOutNotMet',
  code: 12,
} as const satisfies {
  readonly runtimePackageId: string;
  readonly modulePath: string;
  readonly constantName: string;
  readonly code: number;
};
