/**
 * HTTP error-code enums mirrored from
 * `docs/schemas/relay-api.schema.json`.
 *
 * Locked to the schema by
 * `packages/core-relay/tests/errorCodeLock.test.ts`. Each array is a
 * type-preserving tuple so the derived string-literal union matches the
 * schema enum exactly. Any drift (addition / removal / reorder / rename
 * either direction) fails per-code at lock-test time.
 *
 * Consumers:
 *   - `core-api` server-side error throws may reference these arrays for
 *     membership checks without duplicating the schema literals.
 *   - SDK and `app-api` keep their own public `code: string`
 *     APIs.
 *
 * The schema JSON at `docs/schemas/relay-api.schema.json` is the public
 * transport contract reference. This file is a locked copy, not a
 * parallel definition.
 *
 * @module errorCode
 */

// ─────────────────────────────────────────────
// knownPrepareErrorCode
// ─────────────────────────────────────────────

export const KNOWN_PREPARE_ERROR_CODES = [
  'BAD_REQUEST',
  'REQUEST_BODY_TOO_LARGE',
  'PREPARE_AUTH_TIMESTAMP_INVALID',
  'PREPARE_AUTH_NONCE_INVALID',
  'PREPARE_AUTH_TX_KIND_HASH_INVALID',
  'PREPARE_AUTH_TX_KIND_HASH_MISMATCH',
  'PREPARE_AUTH_SIGNATURE_INVALID',
  'PREPARE_AUTH_EXPIRED',
  'PREPARE_AUTH_NONCE_REUSED',
  'PREPARE_SENDER_QUOTA_EXCEEDED',
  'P0_INVALID_BASE64',
  'P0_TX_KIND_TOO_LARGE',
  'P0_INVALID_TX_KIND',
  'INVALID_SLIPPAGE_BPS',
  'INVALID_GAS_MARGIN_BPS',
  'P1_TOO_MANY_COMMANDS',
  'P1_GASCOIN_FORBIDDEN',
  'P1_USER_SETTLE_FORBIDDEN',
  'P1_UNAUTHORIZED_STELIS_CALL',
  'P1_FORBIDDEN_COMMAND',
  'P1_SPONSOR_WITHDRAWAL_FORBIDDEN',
  'UNSUPPORTED_SETTLEMENT_TOKEN',
  'INVALID_ORDER_ID',
  'INSUFFICIENT_BALANCE',
  'CLAIM_WOULD_EXCEED_MAX',
  'INSUFFICIENT_SETTLE_INPUT',
  'SPREAD_EXCEEDED',
  'PAYMENT_COIN_CONFLICT',
  'DRY_RUN_FAILED',
  'DRY_RUN_NO_GAS',
  'UNACCOUNTABLE_WITHDRAWAL',
  'SLIPPAGE_QUERY_FAILED',
  'SLIPPAGE_EXCEEDED',
  'SLIPPAGE_CONVERGENCE_FAILED',
  'L1_TOO_MANY_COMMANDS',
  'L1_FORBIDDEN_COMMAND',
  'L1_NO_SETTLE',
  'L1_MULTIPLE_SETTLE',
  'L1_PARSE_FAILED',
  'L2_EXTRACT_FAILED',
  'L2_WRONG_CONFIG',
  'L2_WRONG_REGISTRY',
  'L2_WRONG_RECIPIENT',
  'L2_EXCESSIVE_CLAIM',
  'L2_HOST_FEE_CAP',
  'L2_PROTOCOL_FEE_MISMATCH',
  'L2_CONFIG_VERSION_MISMATCH',
  'L2_CREDIT_SLIPPAGE_NONZERO',
  'L2_SETTLEMENT_SWAP_PATH_INTEGRITY',
  'L2_NO_SETTLEMENT_SWAP_PATHS_CONFIGURED',
  'L2_UNAUTHORIZED_SETTLEMENT_SWAP_PATH',
  'L2_POLICY_HASH_MISMATCH',
  'L2_ORDER_ID_HASH_MISMATCH',
  'SPONSOR_CAPACITY_UNAVAILABLE',
  'SPONSOR_REFILL_ACCOUNT_UNHEALTHY',
  'NO_SPONSOR_SLOT',
  'PREPARE_OVERLOADED',
  'SPONSOR_LEASE_COMMIT_FAILED',
  'ABUSE_BLOCKED',
  'BLOCK_CHECK_UNAVAILABLE',
  'VAULT_STATE_INCONSISTENT',
  'INTERNAL_ERROR',
] as const;

export type KnownPrepareErrorCode = (typeof KNOWN_PREPARE_ERROR_CODES)[number];

// ─────────────────────────────────────────────
// knownSponsorErrorCode
// ─────────────────────────────────────────────

export const KNOWN_SPONSOR_ERROR_CODES = [
  'BAD_REQUEST',
  'REQUEST_BODY_TOO_LARGE',
  'PREPARED_TX_NOT_FOUND',
  'PREPARED_TX_EXPIRED',
  'SENDER_SIGNATURE_INVALID',
  'RECEIPT_SESSION_MISMATCH',
  'MODE_MISMATCH',
  'REPREPARE_REQUIRED',
  'TAMPERING_DETECTED',
  'L3_NONLOSS_VIOLATION',
  'L3_GAS_BUDGET_EXCEEDED',
  'L3_SIM_GAS_OUT_OF_RANGE',
  'SPONSOR_CAPACITY_UNAVAILABLE',
  'SPONSOR_REFILL_ACCOUNT_UNHEALTHY',
  'SPONSOR_PREFLIGHT_FAILED',
  'SPONSOR_ONCHAIN_FAILED',
  'SPONSOR_CONGESTION',
  'LEASE_EXPIRED',
  'SPONSOR_FAILED',
  'ABUSE_BLOCKED',
  'BLOCK_CHECK_UNAVAILABLE',
] as const;

export type KnownSponsorErrorCode = (typeof KNOWN_SPONSOR_ERROR_CODES)[number];

// ─────────────────────────────────────────────
// knownPromotionPrepareErrorCode
// ─────────────────────────────────────────────

export const KNOWN_PROMOTION_PREPARE_ERROR_CODES = [
  'BAD_REQUEST',
  'REQUEST_BODY_TOO_LARGE',
  'AUTH_FAILED',
  'AUTH_JWT_INVALID',
  'ABUSE_BLOCKED',
  'BLOCK_CHECK_UNAVAILABLE',
  'BAD_TX_KIND',
  'SENDER_ADDRESS_MISMATCH',
  'PROMOTION_NOT_FOUND',
  'PROMOTION_NOT_ACTIVE',
  'NOT_CLAIMED',
  'USE_WINDOW_EXPIRED',
  'FORBIDDEN_COMMAND',
  'GASCOIN_FORBIDDEN',
  'SPONSOR_WITHDRAWAL_FORBIDDEN',
  'DISALLOWED_TARGET',
  'PREPARE_OVERLOADED',
  'SPONSOR_CAPACITY_UNAVAILABLE',
  'SPONSOR_REFILL_ACCOUNT_UNHEALTHY',
  'NO_SPONSOR_SLOT',
  'GAS_EXCEEDS_TX_CAP',
  'DRY_RUN_FAILED',
  'DRY_RUN_NO_GAS',
  'BUDGET_INSUFFICIENT',
  'ENTITLEMENT_NOT_FOUND',
  'ENTITLEMENT_NOT_ACTIVE',
  'ENTITLEMENT_INSUFFICIENT',
  'ENTITLEMENT_CONCURRENT_RESERVATION',
  'PREPARE_STUDIO_USER_QUOTA_EXCEEDED',
  'SPONSOR_LEASE_COMMIT_FAILED',
  'INTERNAL_ERROR',
] as const;

export type KnownPromotionPrepareErrorCode = (typeof KNOWN_PROMOTION_PREPARE_ERROR_CODES)[number];

// ─────────────────────────────────────────────
// knownPromotionSponsorErrorCode
// ─────────────────────────────────────────────

export const KNOWN_PROMOTION_SPONSOR_ERROR_CODES = [
  'BAD_REQUEST',
  'REQUEST_BODY_TOO_LARGE',
  'AUTH_FAILED',
  'AUTH_JWT_INVALID',
  'ABUSE_BLOCKED',
  'BLOCK_CHECK_UNAVAILABLE',
  'SPONSOR_CAPACITY_UNAVAILABLE',
  'SPONSOR_REFILL_ACCOUNT_UNHEALTHY',
  'PREPARED_TX_NOT_FOUND',
  'PREPARED_TX_EXPIRED',
  'SENDER_ADDRESS_MISMATCH',
  'USER_ID_MISMATCH',
  'PROMOTION_NOT_ACTIVE',
  'NOT_CLAIMED',
  'USE_WINDOW_EXPIRED',
  'FORBIDDEN_COMMAND',
  'GASCOIN_FORBIDDEN',
  'DISALLOWED_TARGET',
  'MODE_MISMATCH',
  'PROMOTION_ID_MISMATCH',
  'SENDER_SIGNATURE_INVALID',
  'REPREPARE_REQUIRED',
  'TAMPERING_DETECTED',
  'PREFLIGHT_FAILED',
  'ONCHAIN_REVERT',
  'GAS_EFFECTS_MISSING',
  'CONSUME_FAILED',
  'SPONSOR_FAILED',
] as const;

export type KnownPromotionSponsorErrorCode = (typeof KNOWN_PROMOTION_SPONSOR_ERROR_CODES)[number];
